[package]
name = "echotune"
version = "0.1.0-rc3"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
basic-toml = { version = "0.1.9", optional = true }
getch-rs = "=0.2.0"
lazy_static = "1.5.0"
rodio = { path = "./echotune-rodio", default-features = false, features = ["minimp3", "flac", "vorbis", "wav"] }
serde = { version = "1.0.210", optional = true, features = ["serde_derive"] }
terminal_size = { version = "0.3.0", default-features = false }

[profile.dev.package."*"]
opt-level = 'z'

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.profiling]
inherits = "release"
debug = true
strip = false

[features]
configuration = [ "basic-toml", "serde" ]

